bin/runHarpScan.sh was modified, Now it takes as an afgument the motor name like harp_tc21 Harp default directory was modified, not it is looking files in the /home/epics/DATA/HARP_SCANS/$motor_name, where $motor_name it took as an argument
Now it fits a counter that is set in the Drop Down Menu.

==============================================================================================

At this moment Log entry is not working,
Particularly it gives an error on this line
canvas.exportPNG(imagePath);
error: cannot find symbol
    [javac]             canvas.exportPNG(imagePath);